### ISSUE TITLE
seems fresh install with latest version Doesn't create the config file by default on first launch 

### ISSUE THREAD

**Issue by SerpentDrago** [TastyChickenLegs/ForsakenPowersPlus#1]
I could be wrong , i need someone else to test this , i'm using r2modman , installed , dll is in the correct location , launch game .. doesn't work and seems i don't have the config file . Its also installed on the server . Also if i enable version check , it doesn't let me join with the message i have incorrect version even though its the same both on client and server. 

again , i'll be doing more testing , but i think something is weird . 

I need others to try a FRESH install of the mod , delete the cfg file if they have it , and launch and see if it creates a default one

**Comment by SerpentDrago** [comment]
Ok i manually created the default cfg file . and i still can't figure out if this mod is working or not , nothing happens when i press f8 / f9 visually on the screen . 

also when you say hit f to activate , do you mean while looking at the boss stone ? 

I'm confused

**Comment by SerpentDrago** [comment]
my default cfg file 
![image](https://user-images.githubusercontent.com/21133858/212211319-4472e952-8f47-4d8d-8cc3-42b3ebd8e2b5.png)

**Comment by TastyChickenLegs** [comment]
Ok, sorry I just saw this.  If the config file is not getting created and the nothing is working then the mod is not getting loaded.  Can you send me your game logs.  It would be in the root of the BepInEx folder.  We need to see if the game is getting loaded first.  Some modders will explicitly create mods that state their mod is incompatible with other mods and prohibit them from loading.  The LogOutPut file will define the loaded mods and any errors.

**Comment by SerpentDrago** [comment]
off course , My bad for not already providing it .. i quickly looked though the console output . i should have read the log . 

Well this is weird , i can't find the log file . I've poked around all the folders ... I'm using r2modman . and i guess its deleting or suppressing the logs . cause i can't find them 

![image](https://user-images.githubusercontent.com/21133858/212479693-c8e575cf-5ccb-48e9-90d9-4bc1a864b40c.png)

**Comment by SerpentDrago** [comment]
I get console output when launching the game  but i can't see where thats being stored .

**Comment by SerpentDrago** [comment]
Think i figured out the issue . Passive powers by smoothbrain is STILL getting loaded somehow .. i dont' know how the mod dll file is not there ! if i got to the location listed in the console output . the file it says its loading is NOT THERE . I made sure to remove that mod before installing yours .. is bepinex cacheing something somewhere ? 

![image](https://user-images.githubusercontent.com/21133858/212480444-7c7ee15f-cbeb-434b-804d-fb2cc4d95f6f.png)

**Comment by SerpentDrago** [comment]
So the issue is i had R2modman and Thunderstoremodmanager . the game  when launched "start modded" from r2modman was still using the old  locations for thunderstoremodmanager .

what a mess i made myself . sorry for taking your time . let me see if this fixes it , i'm sure it will .  !

**Comment by TastyChickenLegs** [comment]
It's Ok and I really appreciate all the help.  I use Thunderstore and really like it.  LOL..  So I see in the output that smoothbrain-passivepowers is loading.  That is not this mod.  This is ForsakenPowersPlus  

I mean I have passive powers features in my mod but it's definitely not the same feature set.  The mod you are loading is here  [https://github.com/blaxxun-boop/PassivePowers](url)
